feat: create key pair for ec2

diff --git a/serverless.yml b/serverless.yml
--- a/serverless.yml
+++ b/serverless.yml
@@ -170,7 +170,7 @@ resources:
           KeyName: !Join [ "-", [ {"Ref": "KeyPairName"}, { 'Ref': 'AWS::Region' } ] ]
           IamInstanceProfile:
             Arn: { 'Fn::GetAtt': ['Ec2IAMProfile', 'Arn'] }
-    KafkaKraftCluster9: 
+    KafkaKraftCluster10: 
       Type: "AWS::EC2::Instance"
       Properties:
         AvailabilityZone: { "Fn::Select": ["0", { "Fn::GetAZs": { "Ref": "AWS::Region" } }] }
@@ -198,8 +198,13 @@ resources:
             sudo ln -s kafka_2.12-3.9.0 /opt/kafka
             sudo chown ec2-user:ec2-user /opt/kafka && sudo chmod u+s /opt/kafka
             #sudo rm -rf opt/kafka_2.12-3.9.0
+            set +u
             COUNTRY="ZA"
             export $COUNTRY
+            if [ -z "${COUNTRY}" ]; then
+              echo "Error: COUNTRY variable is not set."
+              exit 1
+            fi
             STATE="Gauteng"
             export $STATE
             ORGANIZATION_UNIT="PX"
@@ -208,6 +213,7 @@ resources:
             export $CITY
             PASSWORD=${password}
             export $PASSWORD
+            set -u
             ls -l 
             ls -l /opt/kafka/
             # Generate TLS Certificate and Stores
@@ -306,6 +312,6 @@ resources:
   Outputs:
     PublicIp:
       Description: Cluster Instance IP Address
-      Value: { "Fn::GetAtt": ["KafkaKraftCluster9", "PublicIp"] }
+      Value: { "Fn::GetAtt": ["KafkaKraftCluster10", "PublicIp"] }
       Export:
         Name: { "Fn::Sub": "${AWS::StackName}-ipaddress" }
