feat: use ansible to run/start multiple apache kafka nodes

diff --git a/iac/ec2/instance/bastion.yml b/iac/ec2/instance/bastion.yml
--- a/iac/ec2/instance/bastion.yml
+++ b/iac/ec2/instance/bastion.yml
@@ -16,58 +16,18 @@ Properties:
       Value: JumpServer
   UserData:
     Fn::Base64: !Sub |
-      #!/bin/bash
-      sudo yum update -y
-      sudo yum install -y aws-cli
-
-      # Install Python and pip if not already present
-      sudo dnf install -y python3 python3-pip
+      #!/bin/bash -xe
+      exec > >(tee /var/log/ansible.log) 2>&1
       
-      # Install Ansible
-      sudo pip3 install ansible
+      # Download and execute with error handling
+      if ! curl -fSL https://raw.githubusercontent.com/teddynted/secure-apache-kafka-kraft-mode-using-sasl-scram-sha-256/refs/heads/main/shell-scripts/ansible.sh -o /tmp/ansible.sh; then
+        echo "ERROR: Failed to download script"
+        exit 1
+      fi
       
-      # Verify installation
-      ansible --version
-
-      PRIVATE_IPS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=*Apache*,*Kafka*" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].PrivateIpAddress" --output text)
-      # Get IPs
-      FIRST_IP=${IP_ARRAY[0]}
-      SECOND_IP=${IP_ARRAY[1]}
-      THIRD_IP=${IP_ARRAY[2]}
-      
-      # Generate SSH key pair non-interactively
-      ssh-keygen -t rsa -b 4096 -f ~/.ssh/kafka_ansible -q -N ""
-      
-      # Set proper permissions
-      chmod 600 ~/.ssh/kafka_ansible
-      chmod 644 ~/.ssh/kafka_ansible.pub
-      chown -R ec2-user:ec2-user ~/.ssh
-
-      # Copy public key to all Kafka nodes
-      for host in $PRIVATE_IPS; do
-        #ssh-copy-id -i ~/.ssh/kafka_ansible.pub -o StrictHostKeyChecking=no ec2-user@$host
-        #ssh -o StrictHostKeyChecking=no ec2-user@$host "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '$(cat ~/.ssh/kafka_ansible.pub)' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
-      done
-      
-      # Test SSH connection
-      echo "Testing SSH connection"
-      #ssh -i ~/.ssh/kafka_ansible ec2-user@FIRST_IP
-
-      # Convert space-separated list into array
-      read -ra IP_ARRAY <<< "$PRIVATE_IPS"
-      
-      # Sort the IPs (optional, for deterministic order)
-      IFS=$'\n' IP_ARRAY=($(sort <<<"${IP_ARRAY[*]}"))
-      unset IFS
-
-      sudo tee inventory.ini << EOF
-      [kafka_nodes]
-      $FIRST_IP
-      $SECOND_IP
-      $THIRD_IP
-        
-      [kafka_nodes:vars]
-      ansible_user=ec2-user
-      ansible_ssh_private_key_file=~/.ssh/kafka_ansible
-      EOF
-      cat inventory.ini
+      chmod +x /tmp/user-data.sh
+      if ! /tmp/ansible.sh; then
+        echo "ERROR: Script execution failed"
+        exit 1
+      fi
+      echo "SUCCESS"
